baseURL = 'https://www.koronacms.de/'
defaultContentLanguage = 'de'
languageCode = 'de'
title = 'Korona CMS'
theme = 'LoveIt'

[params]
    version = "0.2.X"
    description = "Community Management System f端r Sch端ler- und Studentenverbindungen"
    defaultTheme = "auto"
    gitRepo = "https://github.com/pille1842/koronacms.de"

    [params.header]
        [params.header.title]
            logo = "/korona.png"
            name = "Korona CMS"

    [params.footer]
        hugo = false
        license = '<a rel="license external nofollow noopener noreffer" href="https://www.gnu.org/licenses/gpl-3.0" target="_blank">GPL v3</a>'

    [params.home]
        [params.home.profile]
            enable = true
            avatarURL = "/korona.png"
            title = "Korona CMS"
            subtitle = "Community Management System f端r Sch端ler- und Studentenverbindungen"
            social = false

[[menu.main]]
    identifier = "privacy"
    pre = ""
    post = ""
    name = "Datenschutz"
    url = "/privacy/"
    title = ""
    weight = 1

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = '<i class="fab fa-github fa-fw"></i>'
    url = "https://github.com/pille1842/korona"

[author]
    name = "Eric Haberstroh"
    email = "webmaster@koronacms.de"
    link = "http://www.erixpage.de/"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[Permalinks]
    posts = ":filename"
